import { Link } from 'react-router-dom'
import { ArrowRight, Check, HeartHandshake, Leaf, Sparkles, Truck } from 'lucide-react'

const values = [
  [Sparkles, 'Less, but better', 'We look for useful pieces with a little more charm and staying power.'],
  [HeartHandshake, 'People first', 'Friendly help and clear answers should be part of every order.'],
  [Leaf, 'Thoughtful choices', 'We keep an eye out for materials, makers, and products worth keeping.'],
  [Truck, 'Simple service', 'Straightforward shopping from discovery to doorstep.'],
]

export default function About() {
  return (
    <div className="page-shell">
      <section className="relative overflow-hidden bg-brand-950"><img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=1800&q=85" alt="Warm home interior" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-brand-950 via-brand-950/85 to-brand-950/30" /><div className="relative mx-auto grid min-h-[520px] max-w-7xl items-center gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8"><div><p className="inline-flex items-center gap-2 rounded-full border border-gold-400/30 bg-gold-500/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-gold-400"><Sparkles size={14} /> The Nivora way</p><h1 className="mt-6 max-w-3xl font-display text-5xl font-bold leading-[1.06] tracking-tight text-white md:text-6xl">Everyday objects, chosen with feeling.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Nivora Mart is a fictional sample store created around a simple idea: the things we use every day should work well and feel good to have around.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/products" className="btn-gold gap-2">Explore the shop <ArrowRight size={16} /></Link><Link to="/contact" className="btn-outline gap-2 border-white/20 bg-white/10 text-white hover:bg-white/20">Get in touch</Link></div></div><div className="hidden lg:block"><div className="ml-auto max-w-sm rounded-[2rem] border border-white/15 bg-white/[0.08] p-6 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold-400">Our little edit</p><div className="mt-5 grid gap-3">{[['Home moments', 'Pieces that make spaces feel more yours.'], ['On-the-go essentials', 'Travel-friendly favourites for busy days.'], ['Gifts with purpose', 'Useful surprises for the people you love.']].map(([title, text]) => <div key={title} className="rounded-2xl bg-white/10 p-4"><p className="text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-300">{text}</p></div>)}</div></div></div></div></section>
      <section className="border-b border-brand-100 bg-white"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-7 px-4 py-11 text-center sm:px-6 md:grid-cols-4 lg:px-8">{[['One', 'thoughtful edit'], ['Many', 'everyday uses'], ['Simple', 'secure checkout'], ['Always', 'here to help']].map(([number, label]) => <div key={label}><p className="font-display text-4xl font-bold text-brand-800">{number}</p><p className="mt-1 text-sm font-semibold text-slate-500">{label}</p></div>)}</div></section>
      <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="section-kicker">Our point of view</p><h2 className="mt-3 font-display text-4xl font-bold tracking-tight text-slate-950">Good routines begin with good basics.</h2><p className="mt-5 text-base leading-8 text-slate-600">We created Nivora as a fresh sample brand for a calmer kind of online shopping. There is no complicated promise, just a well-considered place to discover things that fit real life.</p><p className="mt-4 text-base leading-8 text-slate-600">From useful home pieces to small travel comforts and easy gifts, the collection is designed to make ordinary moments feel a little more intentional.</p><div className="mt-7 grid gap-3">{['Clear product information', 'Friendly order support', 'Secure account and checkout', 'Simple delivery updates'].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-brand-100 text-brand-800"><Check size={15} /></span>{item}</div>)}</div></div><div className="relative"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1000&q=85" alt="Simple, inviting living space" className="h-[430px] w-full rounded-[2rem] object-cover shadow-2xl shadow-brand-950/15" /><div className="absolute -bottom-5 -left-2 max-w-[230px] rounded-2xl bg-white p-5 shadow-xl sm:-left-6"><p className="font-display text-3xl font-bold text-brand-800">Nivora</p><p className="mt-1 text-sm leading-6 text-slate-500">Everyday market, made a little warmer.</p></div></div></section>
      <section className="bg-brand-50 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="section-kicker">What guides us</p><h2 className="mt-3 section-title md:text-4xl">A softer way to shop.</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([Icon, title, description]) => <article key={title} className="surface-panel p-6"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-50 text-brand-800"><Icon size={22} /></span><h3 className="mt-5 font-display text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p></article>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-brand-950 p-8 text-white md:p-12"><p className="section-kicker text-gold-400">Find something lovely</p><div className="mt-4 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><h2 className="max-w-2xl font-display text-3xl font-bold leading-tight md:text-4xl">Ready to make the everyday feel a little better?</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-200">Browse the Nivora edit and save the things that speak to your routine.</p></div><Link to="/products" className="btn-gold shrink-0 gap-2">Browse products <ArrowRight size={16} /></Link></div></div></section>
    </div>
  )
}
