import { Link } from 'react-router-dom'
import { ArrowRight, Building2, Check, HeartHandshake, Hotel, Leaf, Phone, ShieldCheck, Sparkles, SprayCan, Truck } from 'lucide-react'

const values = [
  [ShieldCheck, 'Quality that holds up', 'Products chosen for daily operational use, not just a shelf display.'],
  [HeartHandshake, 'Partnership mindset', 'Clear communication for busy housekeeping and procurement teams.'],
  [Leaf, 'Thoughtful choices', 'A growing focus on effective, responsible care solutions.'],
  [Truck, 'Reliable movement', 'Practical dispatch planning for facilities across India.'],
]

export default function About() {
  return (
    <div className="page-shell">
      <section className="relative overflow-hidden bg-brand-950"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1800&q=85" alt="Hotel amenity setting" className="absolute inset-0 h-full w-full object-cover opacity-40" /><div className="absolute inset-0 bg-gradient-to-r from-brand-950 via-brand-950/85 to-brand-950/30" /><div className="relative mx-auto grid min-h-[520px] max-w-7xl items-center gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8"><div><p className="inline-flex items-center gap-2 rounded-full border border-gold-400/30 bg-gold-500/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-gold-400"><Sparkles size={14} /> The Bittrif standard</p><h1 className="mt-6 max-w-3xl font-display text-5xl font-bold leading-[1.06] tracking-tight text-white md:text-6xl">Care products for the spaces people remember.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Bittrif Group supports hospitality and facility teams with the practical essentials behind clean, comfortable, guest-ready spaces.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/products" className="btn-gold gap-2">Explore the catalog <ArrowRight size={16} /></Link><a href="tel:+919876543210" className="btn-outline gap-2 border-white/20 bg-white/10 text-white hover:bg-white/20"><Phone size={16} /> Talk to sales</a></div></div><div className="hidden lg:block"><div className="ml-auto max-w-sm rounded-[2rem] border border-white/15 bg-white/[0.08] p-6 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold-400">Who we support</p><div className="mt-5 grid gap-3">{[[Hotel, 'Hospitality', 'Guest rooms, washrooms, and back-of-house'], [SprayCan, 'Facility care', 'Daily cleaning and hygiene programs'], [Building2, 'Business teams', 'Commercial ordering and documentation']].map(([Icon, title, text]) => <div key={title} className="flex gap-3 rounded-2xl bg-white/10 p-4"><Icon size={20} className="shrink-0 text-gold-400" /><div><p className="text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-300">{text}</p></div></div>)}</div></div></div></div></section>

      <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-7 px-4 py-11 text-center sm:px-6 md:grid-cols-4 lg:px-8">{[['500+', 'Business clients'], ['15+', 'Years of service'], ['100+', 'Supply products'], ['50+', 'Cities supported']].map(([number, label]) => <div key={label}><p className="font-display text-4xl font-bold text-brand-800">{number}</p><p className="mt-1 text-sm font-semibold text-slate-500">{label}</p></div>)}</div></section>

      <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="section-kicker">Our approach</p><h2 className="mt-3 font-display text-4xl font-bold tracking-tight text-slate-950">Supply should make the workday feel lighter.</h2><p className="mt-5 text-base leading-8 text-slate-600">Hotels and facilities move quickly. Housekeeping needs dependable cleaners, front-office teams need guest amenities on hand, and procurement needs a process that produces the right paperwork.</p><p className="mt-4 text-base leading-8 text-slate-600">That is why Bittrif brings cleaning systems and hospitality essentials into one practical catalog with business-ready ordering support.</p><div className="mt-7 grid gap-3">{['Clear product information and pack sizes', 'Bulk ordering for regular operational needs', 'GST-ready details at checkout', 'Delivery preferences and notes captured up front'].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-brand-100 text-brand-800"><Check size={15} /></span>{item}</div>)}</div></div><div className="relative"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=85" alt="Professional cleaning supplies" className="h-[430px] w-full rounded-[2rem] object-cover shadow-2xl shadow-slate-900/15" /><div className="absolute -bottom-5 -left-2 max-w-[230px] rounded-2xl bg-white p-5 shadow-xl sm:-left-6"><p className="font-display text-3xl font-bold text-brand-800">One source</p><p className="mt-1 text-sm leading-6 text-slate-500">For cleaning performance and guest comfort.</p></div></div></section>

      <section className="bg-slate-100/80 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="section-kicker">What guides us</p><h2 className="mt-3 section-title md:text-4xl">Professional care, thoughtfully supplied.</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([Icon, title, description]) => <article key={title} className="surface-panel p-6"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-50 text-brand-800"><Icon size={22} /></span><h3 className="mt-5 font-display text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p></article>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-brand-950 p-8 text-white md:p-12"><p className="section-kicker text-gold-400">Start a better supply routine</p><div className="mt-4 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><h2 className="max-w-2xl font-display text-3xl font-bold leading-tight md:text-4xl">Ready to stock the essentials your team depends on?</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-200">Browse the catalog or build your order request with the company, GST, invoice, and delivery details we need to support you well.</p></div><Link to="/products" className="btn-gold shrink-0 gap-2">Browse products <ArrowRight size={16} /></Link></div></div></section>
    </div>
  )
}
