import { useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Mail, MapPin, MessageCircle, Phone, Truck } from 'lucide-react'

export default function Contact() {
  const [searchParams] = useSearchParams()
  const product = searchParams.get('product')
  const subject = product ? `Product question - ${product}` : 'Hello Nivora'
  const emailHref = `mailto:hello@nivoramart.in?subject=${encodeURIComponent(subject)}`

  return (
    <div className="page-shell">
      <section className="relative overflow-hidden bg-brand-950 text-white"><div className="texture-overlay absolute inset-0 opacity-30" /><div className="relative mx-auto grid min-h-[430px] max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-8"><div><p className="text-[11px] font-bold uppercase tracking-[0.22em] text-brand-200">Contact Nivora</p><h1 className="mt-4 max-w-2xl font-display text-5xl font-bold tracking-[-0.05em] md:text-6xl">Let us help you find the right thing.</h1><p className="mt-5 max-w-xl text-base leading-8 text-white/70">Have a product question, need help with an order, or looking for a thoughtful gift? Send us a note and we will point you in the right direction.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.08] p-6 backdrop-blur"><MessageCircle size={30} className="text-brand-200" /><p className="mt-5 text-[11px] font-bold uppercase tracking-[0.18em] text-brand-200">Your message</p>{product ? <><p className="mt-3 font-display text-2xl font-bold text-white">{product}</p><p className="mt-2 text-sm leading-7 text-white/65">We will help with your question about this selected item.</p></> : <><p className="mt-3 font-display text-2xl font-bold text-white">How can we help?</p><p className="mt-2 text-sm leading-7 text-white/65">Tell us what you are looking for and we will get back to you.</p></>}<a href={emailHref} className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-brand-900 hover:bg-brand-100">Email Nivora <ArrowUpRight size={16} /></a></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="section-kicker">We are here</p><h2 className="mt-3 section-title">A little help, whenever you need it.</h2></div><div className="mt-9 grid gap-5 md:grid-cols-3"><a href="tel:+917228041690" className="surface-panel p-6 transition-transform hover:-translate-y-1"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-800"><Phone size={21} /></span><h3 className="mt-6 font-display text-2xl font-bold text-slate-900">Call us</h3><p className="mt-2 text-sm font-bold text-brand-800">+91 72280 41690</p><p className="mt-3 text-sm leading-7 text-slate-600">For product questions, account help, and order support.</p></a><a href={emailHref} className="surface-panel p-6 transition-transform hover:-translate-y-1"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-800"><Mail size={21} /></span><h3 className="mt-6 font-display text-2xl font-bold text-slate-900">Send an email</h3><p className="mt-2 text-sm font-bold text-brand-800">hello@nivoramart.in</p><p className="mt-3 text-sm leading-7 text-slate-600">Share a product link, your question, or your order number.</p></a><article className="surface-panel p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-800"><MapPin size={21} /></span><h3 className="mt-6 font-display text-2xl font-bold text-slate-900">Our base</h3><p className="mt-2 text-sm font-bold text-brand-800">Ahmedabad, Gujarat</p><p className="mt-3 text-sm leading-7 text-slate-600">A fictional sample storefront, designed for shopping across India.</p></article></div></section>
      <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><div className="grid gap-7 rounded-2xl bg-brand-50 p-7 md:grid-cols-[0.8fr_1.2fr] md:items-center md:p-10"><span className="grid h-16 w-16 place-items-center rounded-full bg-brand-900 text-brand-200"><Truck size={27} /></span><div><p className="section-kicker">Order support</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.04em] text-slate-900">Need help with your order?</h2><p className="mt-3 text-sm leading-7 text-slate-600">Include your order number and the email used at checkout. Our support team will help you with delivery updates, product questions, or account access.</p></div></div></section>
    </div>
  )
}
