import { Link } from 'react-router-dom'
import { ArrowUpRight, BadgeCheck } from 'lucide-react'
import { formatPrice } from '../lib/utils'

export default function ProductCard({ product }) {
  const discount = product.original_price ? Math.round((1 - product.price / product.original_price) * 100) : null
  const quotePath = `/contact?product=${encodeURIComponent(product.name)}`

  return <article className="card group flex h-full flex-col overflow-hidden transition-transform duration-300 hover:-translate-y-1"><Link to={`/product/${product.id}`} className="relative block overflow-hidden bg-brand-50"><img src={product.image} alt={product.name} loading="lazy" className="h-44 w-full object-cover transition-transform duration-500 group-hover:scale-105" />{product.category_name && <span className="badge absolute left-3 top-3 bg-white/95 text-brand-800 shadow-sm">{product.category_name}</span>}{discount && <span className="badge absolute right-3 top-3 bg-brand-700 text-white">Save {discount}%</span>}</Link><div className="flex flex-1 flex-col p-4"><div className="flex-1"><Link to={`/product/${product.id}`}><h3 className="font-display text-lg font-bold leading-snug text-slate-900 hover:text-brand-700">{product.name}</h3></Link><p className="mt-1.5 text-xs font-medium text-slate-500">{product.unit || 'Standard pack'}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-600">{product.description || 'Hotel and hospitality supply item available for bulk orders.'}</p></div><div className="mt-4 border-t border-brand-100 pt-3"><div className="flex items-end justify-between gap-2"><div><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-slate-400">Starting price</p><div className="mt-1 flex items-baseline gap-1.5"><span className="text-lg font-bold text-slate-950">{formatPrice(product.price)}</span>{product.original_price && <span className="text-[10px] text-slate-400 line-through">{formatPrice(product.original_price)}</span>}</div></div><span className={`badge text-[10px] ${product.stock > 0 ? 'bg-brand-50 text-brand-800' : 'bg-slate-100 text-slate-500'}`}><BadgeCheck size={11} className="mr-1" />{product.stock > 0 ? 'Available' : 'Enquire'}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Link to={`/product/${product.id}`} className="btn-outline px-2 py-2 text-xs">Details</Link><Link to={quotePath} className="btn-primary gap-1 px-2 py-2 text-xs">Get quote <ArrowUpRight size={13} /></Link></div></div></div></article>
}
